### ISSUE TITLE
Milestones for Russian translation (ru)

### ISSUE THREAD

**Issue by stomar** [ruby/www.ruby-lang.org#214]
Development happens in a dedicated branch: `ru-translation`.

> _Notes_:
> - Track this branch and **never** commit to it. Fork feature branches for PRs.
> - Create PRs for logical units (like e.g. one subdirectory)

Basic setup:
- [x] create development branch _(maintainer)_
- [x] add basic files _(maintainer)_
- [x] config.yml (locales)
- [x] index.html

Content:

> _Notes:_ 
> - add only translated pages, not the original English versions
> - a good start might be: index.html, examples, about, downloads 
- [x] about (note: `license.txt` exists only in `en`)
- [x] community
- [x] documentation
- [x] downloads
- [x] examples
- [x] feeds
- [x] index.html
- [x] libraries
- [x] security

Last addition (since above might take some months...):
- [x] news (most recent articles)

Test and merge:
- [x] test locally
- [x] merge into master
- [x] deploy and test again

Publish:
- [x] add link to 'Russian' to `_includes/languages.html`
- [x] add `ru` to `/index.html`
- [x] add `ru` to Rakefile
- [x] add `ru` to translation status plugin
- [x] announce on www.ruby-lang.org
