### ISSUE TITLE
Milestones for Vietnamese translation (vi)

### ISSUE THREAD

**Issue by stomar** [ruby/www.ruby-lang.org#251]
See `vi-translation` branch.

> _Notes_:
> - Track this branch and **never** commit to it. Fork feature branches for PRs.
> - Create PRs for logical units (like e.g. one subdirectory)

Basic setup:
- [x] create development branch _(maintainer)_
- [x] add `news.rss` and examples directory _(maintainer)_
- [x] config.yml (locales)
- [x] index.html

Content:

> _Notes:_ 
> - add only translated pages, not the original English versions
> - a good start might be: index.html, examples, about, downloads 
- [x] about
- [x] community
- [x] documentation
- [x] downloads
- [x] examples
- [x] feeds
- [x] index.html
- [x] libraries
- [x] news (recent articles)
- [x] security

Test and merge:
- [x] test locally
- [x] merge into master and deploy _(maintainer)_
- [x] test again

Publish:
- [x] add link to 'Vietnamese' to footer _(maintainer)_
- [x] add `vi` to `/index.html` and Rakefile _(maintainer)_
- [x] announce via news post _(maintainer)_
