### ISSUE TITLE
Follow up changes of upstream (ko) 2022-2024

### ISSUE THREAD

**Issue by yous** [ruby/www.ruby-lang.org#2818]
@ruby/www-ruby-lang-org-i18n-ko We can keep track of the following list of pull requests or commits on upstream. See #1894.

- [ ] [en/privacy/index.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/privacy/index.md)
<details>
<summary>Translation Finished (TL;DR)</summary>

- [x] [2021-12-25-ruby-3-1-0-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-12-25-ruby-3-1-0-released.md) (#2781)
- [x] [2022-04-03-ruby-3-2-0-preview1-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-04-03-ruby-3-2-0-preview1-released.md) (#2817)
- [x] [2021-05-02-os-command-injection-in-rdoc.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-05-02-os-command-injection-in-rdoc.md) (#2821)
- [x] [2021-07-07-ruby-2-6-8-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-07-07-ruby-2-6-8-released.md) (#2856)
- [x] [2021-07-07-ruby-2-7-4-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-07-07-ruby-2-7-4-released.md) (#2856)
- [x] [2021-07-07-ruby-3-0-2-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-07-07-ruby-3-0-2-released.md) (#2856)
- [x] [2021-07-07-starttls-stripping-in-net-imap.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-07-07-starttls-stripping-in-net-imap.md) (#2856)
- [x] [2021-07-07-trusting-pasv-responses-in-net-ftp.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-07-07-trusting-pasv-responses-in-net-ftp.md) (#2856)
- [x] [2021-08-03-fukuoka-ruby-award-2022.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-08-03-fukuoka-ruby-award-2022.md) (#2887)
- [x] #2686 (#2888)
- [x] #2692 (#2888)
- [x] #2699 (#2888)
- [x] #2703 (#2888)
- [x] [2021-11-09-ruby-3-1-0-preview1-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-11-09-ruby-3-1-0-preview1-released.md) (#2889)
- [x] [2021-11-15-date-parsing-method-regexp-dos-cve-2021-41817.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-11-15-date-parsing-method-regexp-dos-cve-2021-41817.md) (#2892)
- [x] #2915 (#2943)
- [x] #2911 (#2943)
- [x] #2930 (#2942)
- [x] #2732 (#2945)
- [x] #2784 (#2945)
- [x] `/en/security/index.md`  (#2945)
  - #1410
  - 5a7b6e7
  - #2857
  - #2893
- [x] #2875 (#2944)
- [x] #2900 (#2944)
- [x] #2913 (#2944)
- [x] #2899 (#2945)
- [x] [2022-11-22-http-response-splitting-in-cgi-cve-2021-33621.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-11-22-http-response-splitting-in-cgi-cve-2021-33621.md) (#2947)
- [x] 2022-11-24 (#2947)
  - [2022-11-24-ruby-2-7-7-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-11-24-ruby-2-7-7-released.md)
  - [2022-11-24-ruby-3-0-5-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-11-24-ruby-3-0-5-released.md)
  - [2022-11-24-ruby-3-1-3-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-11-24-ruby-3-1-3-released.md)
- [x] 2021-11-24 (#2949)
  - [2021-11-24-buffer-overrun-in-cgi-escape_html-cve-2021-41816.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-11-24-buffer-overrun-in-cgi-escape_html-cve-2021-41816.md)
  - [2021-11-24-cookie-prefix-spoofing-in-cgi-cookie-parse-cve-2021-41819.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-11-24-cookie-prefix-spoofing-in-cgi-cookie-parse-cve-2021-41819.md)
  - [2021-11-24-ruby-2-6-9-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-11-24-ruby-2-6-9-released.md)
  - [2021-11-24-ruby-2-7-5-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-11-24-ruby-2-7-5-released.md)
  - [2021-11-24-ruby-3-0-3-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2021-11-24-ruby-3-0-3-released.md)
- [x] [2022-02-18-ruby-3-1-1-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-02-18-ruby-3-1-1-released.md) (#2951)
- [x] 2022-04-12 (#2948)
  - [2022-04-12-buffer-overrun-in-string-to-float-cve-2022-28739.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-04-12-buffer-overrun-in-string-to-float-cve-2022-28739.md)
  - [2022-04-12-double-free-in-regexp-compilation-cve-2022-28738.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-04-12-double-free-in-regexp-compilation-cve-2022-28738.md)
  - [2022-04-12-ruby-2-6-10-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-04-12-ruby-2-6-10-released.md)
  - [2022-04-12-ruby-2-7-6-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-04-12-ruby-2-7-6-released.md)
  - [2022-04-12-ruby-3-0-4-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-04-12-ruby-3-0-4-released.md)
  - [2022-04-12-ruby-3-1-2-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-04-12-ruby-3-1-2-released.md)
- [x] [2023-02-08-ruby-3-2-1-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-02-08-ruby-3-2-1-released.md) (#2979)
- [x] #2980 (#2982)
- [x] `/en/documentation/ruby-from-other-languages/`
  - [x] [`to-ruby-from-c-and-cpp/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/ruby-from-other-languages/to-ruby-from-c-and-cpp/index.md) (#2995)
  - [x] [`to-ruby-from-perl/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/ruby-from-other-languages/to-ruby-from-perl/index.md) (#2995)
  - [x] [`to-ruby-from-php/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/ruby-from-other-languages/to-ruby-from-php/index.md) (#2995)
- [x] `/en/downloads/`
  - [x] [`branches/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/downloads/branches/index.md) (#2993)
  - [x] [`releases/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/downloads/releases/index.md) (#2993)
- [x] #2970 (#2993)
- [x] #2981 (#2993)
- [x] [2023-03-28-redos-in-uri-cve-2023-28755.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-03-28-redos-in-uri-cve-2023-28755.md) (#3007)
- [x] 2023-03-30 (#3022, #3023)
  - [2023-03-30-redos-in-time-cve-2023-28756.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-03-30-redos-in-time-cve-2023-28756.md)
  - [2023-03-30-ruby-2-7-8-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-03-30-ruby-2-7-8-released.md)
  - [2023-03-30-ruby-3-0-6-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-03-30-ruby-3-0-6-released.md)
  - [2023-03-30-ruby-3-1-4-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-03-30-ruby-3-1-4-released.md)
  - [2023-03-30-ruby-3-2-2-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-03-30-ruby-3-2-2-released.md)
- [x] #2996 (#3036)
- [x] #3113 (#3114)
- [x] `/en/documentation/faq/`
  - [x] [`index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/faq/index.md) (#2998)
  - [x] [`1/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/faq/1/index.md) (#2998)
  - [x] [`2/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/faq/2/index.md) (#3000)
  - [x] [`3/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/faq/3/index.md) (#3005)
  - [x] [`4/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/faq/4/index.md) (#3027)
  - [x] [`5/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/faq/5/index.md) (#3028)
  - [x] [`6/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/faq/6/index.md) (#3033)
  - [x] [`7/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/faq/7/index.md) (#3034)
  - [x] [`8/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/faq/8/index.md) (#3040)
  - [x] [`9/index.md`](https://github.com/ruby/www.ruby-lang.org/tree/master/en/documentation/faq/9/index.md) (#3040)
  - [x] [`10/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/faq/10/index.md) (#3040)
  - [x] [`11/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/documentation/faq/11/index.md) (#3040)
- [x] `/en/community/`
  - [x] [`mailing-lists/ruby-talk-guidelines/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/community/mailing-lists/ruby-talk-guidelines/index.md) (#3043)
- [x] #3058 #3060 (#3062)
- [x] [2023-06-29-redos-in-uri-CVE-2023-36617.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-06-29-redos-in-uri-CVE-2023-36617.md) (#3094)
- [x] #3126 (#3127)
- [x] [2023-11-12-ruby-3-3-0-preview3-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-11-12-ruby-3-3-0-preview3-released.md) (#3139)
- [x] [en/news/_posts/2023-12-11-ruby-3-3-0-rc1-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-12-11-ruby-3-3-0-rc1-released.md) (#3153)
- [x] https://github.com/ruby/www.ruby-lang.org/pull/3159 (#3162)
- [x] #3165 (https://github.com/ruby/www.ruby-lang.org/pull/3169)
- [x] #3178, #3180 (#3181)
- [x] #3184 (#3185, #3186)
- [x] #3183 (#3191)
- [x] #3197 (#3200)
- [x] [2024-03-21-buffer-overread-cve-2024-27280](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-03-21-buffer-overread-cve-2024-27280.md) (#3205)
- [x] [2024-03-21-rce-rdoc-cve-2024-27281](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-03-21-rce-rdoc-cve-2024-27281.md) (#3205)
- [x] #3214 (#3215)
- [x] [CVE-2024-27282: Arbitrary memory address read vulnerability with Regex search](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-04-23-arbitrary-memory-address-read-regexp-cve-2024-27282.md) (#3230)
- [x] [Ruby 3.0.7 Released](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-04-23-ruby-3-0-7-released.md) (#3230)
- [x] [Ruby 3.1.5 Released](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-04-23-ruby-3-1-5-released.md) (#3230)
- [x] [Ruby 3.2.4 Released](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-04-23-ruby-3-2-4-released.md) (#3230)
- [x] [Ruby 3.3.1 Released](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-04-23-ruby-3-3-1-released.md) (#3230)
- [x] #3175 (#3229)
- [x] #3226 (#3230)
- [x] #3239 (#3242)
- [x] #3240 (#3243)
- [x] #3260 (#3268)
- [x] #3264 (#3269)
- [x] #3263 (#3270)
- [x] #3277 (#3279, #3282)
- [x] #3286 (#3287)
- [x] #3275 (#3288)
- [x] #3292, 88ad266 (#3293)
- [x] #3276, #3295 (#3296)
- [x] #3304 (#3306)
- [x] #3314 (#3316)
- [x] #3323, #3324 (#3327)
- [x] #3332 (#3334)
- [x] #3333 (#3334)
- [x] #3311 (#3338)
- [x] #3348 (#3353)
- [x] #3355 (#3363)
- [x] #3359, #3360 (#3362)
- [x] #3389 (#3391)
- [x] #3385 (#3390)
- [x] #3379 #3380 #3381 #3382 #3384 (#3392)
- [x] [en/news/_posts/2024-10-28-redos-rexml-cve-2024-49761.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-10-28-redos-rexml-cve-2024-49761.md) (#3402)
- [x] [en/news/_posts/2024-10-30-ruby-3-2-6-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-10-30-ruby-3-2-6-released.md) (#3408)
- [x] #3416 (#3417)
- [x] #3352 (#3428)
- [x] #3424 (#3429)
- [x] #3425 (#3433)
- [x] #3435 #3436 #3437 (#3438)
- [x] #3442, #3449 (#3443)
- [x] #3445 (#3446)

</details>

**Comment by yous** [comment]
`/en/security/index.md`

- #1410
- 5a7b6e7
- #2857

**Comment by yous** [comment]
#2813 was handled by #2817. 😄

**Comment by riseshia** [comment]
oops 😇

**Comment by riseshia** [comment]
#2900

**Comment by yous** [comment]
- [2022-11-24-ruby-2-7-7-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-11-24-ruby-2-7-7-released.md)
- [2022-11-24-ruby-3-0-5-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-11-24-ruby-3-0-5-released.md)
- [2022-11-24-ruby-3-1-3-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2022-11-24-ruby-3-1-3-released.md)

**Comment by riseshia** [comment]
#2913

**Comment by yous** [comment]
- #2899

**Comment by yous** [comment]
- #2915

**Comment by yous** [comment]
- #2911

**Comment by riseshia** [comment]
- #2930

**Comment by yous** [comment]
- #2970

**Comment by hsbt** [comment]
@yous Thanks always ❤️

**Comment by yous** [comment]
- #2980

**Comment by riseshia** [comment]
- #2981

**Comment by yous** [comment]
Now we can translate [`en/downloads/branches/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/downloads/branches/index.md) as #2986 is merged.

**Comment by yous** [comment]
Now we can translate [`/en/downloads/releases/index.md`](https://github.com/ruby/www.ruby-lang.org/blob/master/en/downloads/releases/index.md) as #2987 is merged.

**Comment by riseshia** [comment]
- 52f7d795334a29dff78b3c0c4f0920d642281a94

**Comment by yous** [comment]
- 2023-03-30
  - [2023-03-30-redos-in-time-cve-2023-28756.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-03-30-redos-in-time-cve-2023-28756.md)
  - [2023-03-30-ruby-2-7-8-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-03-30-ruby-2-7-8-released.md)
  - [2023-03-30-ruby-3-0-6-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-03-30-ruby-3-0-6-released.md)
  - [2023-03-30-ruby-3-1-4-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-03-30-ruby-3-1-4-released.md)
  - [2023-03-30-ruby-3-2-2-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-03-30-ruby-3-2-2-released.md)

**Comment by yous** [comment]
- #2996

**Comment by yous** [comment]
- [2023-06-29-redos-in-uri-CVE-2023-36617.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-06-29-redos-in-uri-CVE-2023-36617.md)

**Comment by riseshia** [comment]
#3113

**Comment by yous** [comment]
- #3126

**Comment by yous** [comment]
- [ ] [2023-11-12-ruby-3-3-0-preview3-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-11-12-ruby-3-3-0-preview3-released.md)

**Comment by yous** [comment]
- [en/privacy/index.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/privacy/index.md)

**Comment by yous** [comment]
- [en/news/_posts/2023-12-11-ruby-3-3-0-rc1-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-12-11-ruby-3-3-0-rc1-released.md)

**Comment by riseshia** [comment]
- https://github.com/ruby/www.ruby-lang.org/pull/3159

**Comment by yous** [comment]
- #3165

**Comment by yous** [comment]
- #3178

**Comment by riseshia** [comment]
#3184

**Comment by riseshia** [comment]
https://github.com/ruby/www.ruby-lang.org/pull/3183

**Comment by riseshia** [comment]
#3197

**Comment by riseshia** [comment]
- https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-03-21-buffer-overread-cve-2024-27280.md
- https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-03-21-rce-rdoc-cve-2024-27281.md

**Comment by hsbt** [comment]
@yous @riseshia Thanks always ❤️

**Comment by yous** [comment]
- #3214

**Comment by riseshia** [comment]
- [CVE-2024-27282: Arbitrary memory address read vulnerability with Regex search](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-04-23-arbitrary-memory-address-read-regexp-cve-2024-27282.md)
- [Ruby 3.0.7 Released](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-04-23-ruby-3-0-7-released.md)
- [Ruby 3.1.5 Released](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-04-23-ruby-3-1-5-released.md)
- [Ruby 3.2.4 Released](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-04-23-ruby-3-2-4-released.md)
- [Ruby 3.3.1 Released](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-04-23-ruby-3-3-1-released.md)

**Comment by yous** [comment]
- #3175

**Comment by riseshia** [comment]
- https://github.com/ruby/www.ruby-lang.org/pull/3226

**Comment by riseshia** [comment]
- https://github.com/ruby/www.ruby-lang.org/pull/3239
- https://github.com/ruby/www.ruby-lang.org/pull/3240

**Comment by yous** [comment]
Maybe we should add `cx_id` too to make search work.

- #3253

**Comment by yous** [comment]
As I see, the value of `cx_id` is same with other languages, but I'm not sure. 🤔

**Comment by riseshia** [comment]
```
$ git grep cx_id
_data/locales/de.yml:  cx_id: '008918821236166936739:xplclbf3sh0'
_data/locales/en.yml:  cx_id: '013598269713424429640:g5orptiw95w'
_data/locales/es.yml:  cx_id: '013598269713424429640:g5orptiw95w'
_data/locales/fr.yml:  cx_id: '016749562256550695330:efcmgh3a1ac'
_data/locales/ja.yml:  cx_id: '008288045305770251182:fvruzsaknew'
_data/locales/tr.yml:  cx_id: '011743037637077038592:5tuc9cqilws'
```

**Comment by riseshia** [comment]
https://github.com/ruby/www.ruby-lang.org/pull/3255 add fallback to en cx_id

**Comment by riseshia** [comment]
#3260

**Comment by riseshia** [comment]
#3263
#3264

**Comment by riseshia** [comment]
#3277

**Comment by riseshia** [comment]
#3286

**Comment by riseshia** [comment]
#3275

**Comment by yous** [comment]
- #3292

**Comment by riseshia** [comment]
#3276

**Comment by riseshia** [comment]
#3314

**Comment by yous** [comment]
- #3323, #3324

**Comment by riseshia** [comment]
https://github.com/ruby/www.ruby-lang.org/pull/3311

**Comment by riseshia** [comment]
https://github.com/ruby/www.ruby-lang.org/pull/3345 -> https://github.com/ruby/www.ruby-lang.org/pull/3346

**Comment by yous** [comment]
- #3348

**Comment by yous** [comment]
- #3355

**Comment by riseshia** [comment]
#3359

**Comment by riseshia** [comment]
#3360

**Comment by riseshia** [comment]
- #3379 #3380 #3381 #3382

**Comment by riseshia** [comment]
#3389 ?

**Comment by yous** [comment]
- #3385

**Comment by yous** [comment]
- [en/news/_posts/2024-10-28-redos-rexml-cve-2024-49761.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-10-28-redos-rexml-cve-2024-49761.md)

**Comment by yous** [comment]
- [en/news/_posts/2024-10-30-ruby-3-2-6-released.md](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2024-10-30-ruby-3-2-6-released.md)

**Comment by riseshia** [comment]
#3416

**Comment by riseshia** [comment]
#3352

**Comment by riseshia** [comment]
#3424

**Comment by riseshia** [comment]
#3425

**Comment by riseshia** [comment]
#3435 #3436

**Comment by riseshia** [comment]
#3442

**Comment by riseshia** [comment]
#3445

**Comment by riseshia** [comment]
I think it's the time to open new issue for this XD.

**Comment by riseshia** [comment]
Continued on #3461
