### ISSUE TITLE
Milestones for Khmer translation (km)

### ISSUE THREAD

**Issue by stomar** [ruby/www.ruby-lang.org#699]
Development happens in a dedicated branch: `km-translation`.

> _Notes_:
> - Track this branch and **never** commit to it.
> - Fork feature branches from `km-translation` for PRs.
> - Create PRs for logical units (like e.g. one subdirectory).
> - Preview on your local machine.
> - Start slow to allow for feedback.

Basic setup:
- [x] create development branch _(maintainer)_
- [x] add basic files _(maintainer)_ (`index.html`, `feeds/news.rss`, examples)
- [ ] config.yml (locales)
- [ ] index.html

Content:

> _Notes:_ 
> - add only translated pages, not the original English versions
> - a good start might be: index.html, examples, about, downloads 
- [ ] about (note: `license.txt` exists only in `en`)
- [ ] community
- [ ] documentation
- [ ] downloads (note: `mirrors` exists only in `en`)
- [ ] examples
- [ ] feeds
- [ ] index.html
- [ ] installation
- [ ] libraries
- [ ] security

Last addition (since above might take some months...):
- [ ] news (most recent articles)

Test and merge:
- [ ] test locally
- [ ] merge into master
- [ ] deploy and test again

Publish:
- [ ] add link to 'Khmer' to `_includes/languages.html`
- [ ] add `km` to `/index.html`
- [ ] add `km` to Rakefile
- [ ] add `km` to translation status plugin
- [ ] announce on www.ruby-lang.org

**Comment by budmc29** [comment]
I'll comment here since I don't know where would be the appropriate place to ask.

@stoma Is the website accepting new translations? If yes, I could start working on doing a Romanian translation using the above milestones you set up.

**Comment by mjago** [comment]
@stomar thought you may miss this since issue is closed

**Comment by stomar** [comment]
Generally, new translations are possible. But please read my comments in #670. It's a lot of work, both initially and later on keeping up with news post translations, so a motivated and reliable team is needed.

Further discussions should be moved to a new issue.

**Comment by Bunlong** [comment]
Dear all, I would like request to add Khmer translation (km) on www.ruby-lang.org again. How do you think?
